### ISSUE TITLE
the need

### ISSUE THREAD

**Issue by MGTV01** [prshanilka/wcoinbot#1]
The robot is great. But it's good ADD_TAPS_ON_TURBO. Also add APPLY_DAILY_ENERGY and APPLY_DAILY_TURBO

**Comment by prshanilka** [comment]
Thank you for your feedback! I'm glad you like the robot. I plan to add these features in the future. Stay tuned!

**Comment by byanonim** [comment]
Please add auto claim

**Comment by shelllshock** [comment]
Add autoclaim please! Tnx!

**Comment by shelllshock** [comment]
Bot is perfect!
