### ISSUE TITLE
eRRor

### ISSUE THREAD

**Issue by mrdarkerr** [prshanilka/wcoinbot#3]
WCoinBot | 2024-06-17 11:00:57 | ERROR    | 129 - god_of_nigga | Unknown error while Tapping: 400, message='Bad Request', url=URL('https://starfish-app-fknmx.ondigitalocean.app/wapi/api/users/134674?timestamp=118057&hash=query_id=AAH1_448AwAAAPX_jjw0xWB2&user=%7B%22id%22:74455541,%22first_name%22:%22Nigga%22,%22last_name%22:%22%22,%22username%22:%22God_of_nigga%22,%22language_code%22:%22en%22,%22allows_write_to_pm%22:true%7D&auth_date=11862056&hash=b79e64701817e7f187b0e66fb11f71501e3928f75da20aa70787d77a3ff') | Response text: {"data":null,"error":{"status":400,"name":"BadRequestError","message":"Update request is malformed","details":{}}}...

**Comment by wuzer** [comment]
same error

**Comment by shelllshock** [comment]
pls? fix!

**Comment by prshanilka** [comment]
fixed
